name: bw_pm
description: "BindWorks - Blood Pressure Monitoring"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc_concurrency: 0.3.0
  bloc_effects: 2.0.1
  flutter_bloc: 9.1.1

  # DI
  get_it: 9.2.0

  # Logging
  talker: 5.1.13
  talker_flutter: 5.1.13

  # Bluetooth
  flutter_blue_plus: 2.1.1
  permission_handler: 12.0.1

  # Storage
  shared_preferences: 2.5.4

  # Utilities
  uuid: 4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
